---
# tasks file for submariner-cluster1-broker
- name: Register the private address of the EC2 host
  shell: hostname -I | awk "{print \$1}"
  register: node_ip


- name: Change the owner of the home dir
  shell: "sudo chown -hR {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/"

- name: Verify kubectl cmd
  command: kubectl get pods --all-namespaces --kubeconfig /home/{{ ansible_user }}/config


- name: Install Submariner
  shell: |
    curl -Ls https://get.submariner.io/ > /home/{{ ansible_user }}/install-sub
    chmod +x /home/{{ ansible_user }}/install-sub
    VERSION=devel /home/{{ ansible_user }}/install-sub
    sudo cp /root/.local/bin/subctl /usr/local/bin/subctl

# Uncomment for Active/Active branch
#- name: Download the custom subctl binary
#  shell: |
#    curl {{ submariner_subctl_binary_url }} --output /usr/local/bin/subctl
#    chmod +x /usr/local/bin/subctl

- name: Download the custom subctl binary
  shell: |
    curl {{ submariner_subctl_binary_url }} --output /usr/local/bin/subctl
    chmod +x /usr/local/bin/subctl

- name: Label the node as a gateway
  command: kubectl label node {{ hostname }} submariner.io/gateway=true --overwrite --kubeconfig /home/{{ ansible_user }}/config

- name: Pause for 5s to allow for stabilization
  pause:
    seconds: 5

# Uncomment for Active/Active branch
- name: Start the submariner broker
  shell: |
    subctl --kubeconfig /home/{{ ansible_user }}/config deploy-broker \
     --components service-discovery,connectivity \
    --globalnet \
#    --repository {{ submariner_broker_repository }}


- name: Wait for submariner-operator to become ready
  command: kubectl wait --for=condition=ready pod -l name=submariner-operator --timeout=60s -n submariner-operator --kubeconfig /home/{{ ansible_user }}/config

- name: Pause for 20s to allow for stabilization
  pause:
    seconds: 20

- name: Change the owner of the home dir
  shell: "sudo chown -hR {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/"

- fetch:
    src: /home/{{ ansible_user }}/broker-info.subm
    dest: ./
    flat: true

# Uncomment for Active/Active branch
#- name: Download the custom subctl binary
#  shell: |
#    curl {{ submariner_subctl_binary_url }} --output /usr/local/bin/subctl
#    chmod +x /usr/local/bin/subctl

- name: Pause for 10s to allow for stabilization
  pause:
    seconds: 10

# Uncomment for active/active HA experimental branch
- name: Join the submariner node to the broker
  shell: |
    subctl --kubeconfig /home/{{ ansible_user }}/config \
    join /home/{{ ansible_user }}/broker-info.subm \
    --clusterid {{ hostname }} \
    --clustercidr={{ submariner_cluster_cidr }} \
    --nattport 4500 \
    --cable-driver {{ submariner_cable_driver }} \
    --natt=false \
#    --multi-active-gateway=true \
#    --image-override=submariner-operator={{ submariner_image_override }}/submariner-operator:devel \
#    --image-override=submariner-globalnet={{ submariner_image_override }}/submariner-globalnet:devel \
#    --image-override=submariner-gateway={{ submariner_image_override }}/submariner-gateway:devel \
#    --image-override=submariner-route-agent={{ submariner_image_override }}/submariner-route-agent:devel

- name: Pause for 60s to allow for stabilization
  pause:
    seconds: 60

- name: Ensure the submariner-gateway pod is in ready state
  shell: kubectl wait --for=condition=ready pod -l app=submariner-gateway --timeout=120s -n submariner-operator --kubeconfig /home/{{ ansible_user }}/config
