---
# tasks file for k8s-skupper-spokes
- name: Register the private address of the EC2 host
  shell: hostname -I | awk "{print \$1}"
  register: node_ip

- copy:
    src: ./skupper-keys-tmp/secret-{{ hostvars[inventory_hostname].ec2_name }}.yaml
    dest: /home/{{ ansible_user }}/secret-{{ hostvars[inventory_hostname].ec2_name }}.yaml

- name: Install k3s on the hub node
  shell: curl -sfL https://get.k3s.io | sh -
  ignore_errors: True

- name: Wait for kubeconfig to be created
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    timeout: 30
  ignore_errors: True

- name: Creating the .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube/
    state: directory

- name: Copying kubeconfig to .kube directory
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config

- name: Change the owner of .kube/config
  shell: "sudo chown -R $(id -u {{ ansible_user }}):$(id -g {{ ansible_user }}) /home/{{ ansible_user }}/.kube/"

- name: Fixup the kubeconfig server address
  ansible.builtin.replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: '127.0.0.1'
    replace: '{{ node_ip.stdout }}'

- name: export KUBECONFIG
  shell: export KUBECONFIG=/home/{{ ansible_user }}/.kube/config

- name: Verify kubectl
  command: kubectl get pods --all-namespaces

- name: Create skupper namespace and set context
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl create namespace {{ hostvars[inventory_hostname].ec2_name }}
    kubectl config set-context --current --namespace {{ hostvars[inventory_hostname].ec2_name }}
  become_user: "{{ ansible_user }}"

- name: Install Skupper
  shell: |
    curl https://skupper.io/install.sh | sh

- name: Pause for 10 seconds for Skupper post install
  pause:
    seconds: 10

- name: Copy Skupper binary
  shell: sudo cp /root/.local/bin/skupper /usr/local/bin/skupper

- name: Initialize Skupper
  command: skupper init
  become_user: "{{ ansible_user }}"

- name: Pause for 30 seconds for Skupper pods to initiate
  pause:
    seconds: 30

- name: Wait for Skupper pods to become ready
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=skupper-router --timeout=120s
  become_user: "{{ ansible_user }}"

- name: Create spoke secrets
  command: skupper link create /home/{{ ansible_user }}/secret-{{ hostvars[inventory_hostname].ec2_name }}.yaml
  become_user: "{{ ansible_user }}"
  with_items:  "{{ groups['spokeNode'] }}"

