# deploy to ec2 instances
- hosts: localhost
  vars_files: 
    - credentials.yml
    - vars.yml
  tasks:
    - name: Installing boto library
      pip:
         name: boto
         state: present
    - name: Making Security group for multi-node cluster
      amazon.aws.ec2_group:
         name: "{{ secgroup_name }}"
         aws_region: "{{ aws_region }}"
         description: "{{ security_group_description }}"
         vpc_id: "{{ vpc_id }}"
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         rules:
            - proto: all
              cidr_ip: "0.0.0.0/0"

    - name: Launching Broker Node
      amazon.aws.ec2_instance:
         name: "broker-node"
         aws_region: "{{ aws_region }}"
         key_name: "{{ aws_key_name }}"
         instance_type: "{{ aws_instance_type }}"
         image_id: "{{ aws_image_id }}"
         security_group: "{{ secgroup_name }}"
         network:
           assign_public_ip: true
         subnet_id: "{{ aws_subnet }}"
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         state: running
         wait: true
      register: brokerIp

    - name: Updating the broker node's public ip in inventory
      lineinfile:
         path: "{{ inventory_location }}"
         regexp: "brokerNode"
         line: "[brokerNode]\n{{ brokerIp['instances'][0]['public_ip_address']}} ansible_user={{ ansible_user }} ansible_connection=ssh\n"

    - name: Launching Cluster Nodes
      amazon.aws.ec2_instance:
         name: "cluster-node-{{ item+1 }}"
         aws_region: "{{ aws_region }}"
         key_name: "{{ aws_key_name }}"
         instance_type: "{{ aws_instance_type }}"
         image_id: "{{ aws_image_id }}"
         security_group: "{{ secgroup_name }}"
         network:
           assign_public_ip: true
         subnet_id: "{{ aws_subnet }}"
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         state: running
         wait: true
      register: nodeIP
      loop: "{{ range(0, node_count | int) }}"
      
    - name: Updating the worker node's public ip in inventory
      lineinfile:
         path: "{{ inventory_location }}"
         regexp: "clusterNode"
         line: "[clusterNode]\n{{ nodeIP['results'][item]['instances'][0]['public_ip_address']}} ansible_user={{ ansible_user }} ansible_connection=ssh"
      loop: "{{ range(0, node_count | int) }}"
