---
# tasks file for deploy-grafana
- name: Install Packages
  dnf:
    name:
      - docker
      - wget
    state: latest
    update_cache: yes

- name: Start a container runtime
  shell: sudo systemctl start docker

- name: Start the Grafana/Graphite Pod
  shell: |
    docker run -d \
        --name graphite-grafana \
        --restart always \
        -p 80:80 \
        -p 2003-2004:2003-2004 \
        quay.io/networkstatic/graphite-grafana

- name: Pause for 10s for the Graphite/Grafana stack to initialize
  pause:
    seconds: 10

- name: Install YQ
  shell: |
    sudo dnf -y install wget
    sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    sudo chmod a+x /usr/local/bin/yq

- name: Patch the traefik svc port to fix the overlap with the grafana bind address
  shell: |
    kubectl patch svc traefik --type merge -p '{"spec":{"ports": [{"port": 81,"name":"web"}]}}' -n kube-system --kubeconfig /home/{{ ansible_user }}/config

- name: Register the public address of the EC2 host
  shell: wget -qO- https://api.ipify.org; echo
  register: GRAFANA_PUB_ADDRESS

- name: Display the Grafana Public URL
  debug:
    msg: "Grafana URL is at http://{{ GRAFANA_PUB_ADDRESS.stdout }}"

