---
# tasks file for deploy-netserver-group1
- name: Ensure the submariner-gateway pod is in ready state
  shell: kubectl wait --for=condition=ready pod -l app=submariner-gateway --timeout=120s -n submariner-operator --kubeconfig /home/{{ ansible_user }}/config

- name: Label worker1 node in cluster-2 for the Netserver StatefulSet
  shell: kubectl label nodes {{ hostname }} netserver-group1=true --overwrite --kubeconfig /home/{{ ansible_user }}/config

- name: Create the Netserver StatefulSet and service listening on TCP/12865
  shell: |
    cat <<EOF > /home/{{ ansible_user }}/netserver-group1-ss.yaml
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: netserver-group1
    spec:
      serviceName: "netserver-group1"
      replicas: 1
      selector:
        matchLabels:
            app.kubernetes.io/instance: netserver-group1
            app.kubernetes.io/name: netserver-group1
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: netserver-group1
            app.kubernetes.io/name: netserver-group1
        spec:
          nodeSelector:
            netserver-group1: "true"
          containers:
          - name: netserver-group1
            image: quay.io/networkstatic/netserver
            args: ["-D"]
            ports:
            - containerPort: 12865
              name: netserver
    EOF

- name: Starting the Netperf daemonset
  command: kubectl apply -f /home/{{ ansible_user }}/netserver-group1-ss.yaml --kubeconfig /home/{{ ansible_user }}/config

- name: Pause for 10s to allow for stabilization
  pause:
    seconds: 10

- name: Register the exported Netserver address
  shell: kubectl get pod netserver-group1-0 -o custom-columns=IP:status.podIP --no-headers --kubeconfig /home/{{ ansible_user }}/config
  register: netserver_target_group1

- name: Display group1 Netserver target address
  debug:
    msg: "NetServer group1 target address is: {{ netserver_target_group1.stdout }}"
