# roles get branched from here
- hosts: brokerNode
  vars_files:
    - vars.yml
  roles:
    - role: k8s-broker-cluster1

- hosts: secondaryGatewayNode
  vars_files:
    - vars.yml
  roles:
    - role: k8s-cluster1-secondary-gateway

- hosts: cluster2PerfCollectorNode
  vars_files:
    - vars.yml
  roles:
    - role: k8s-cluster2-perf-collector-master

- hosts: cluster2SecondaryGatewayNode
  vars_files:
    - vars.yml
  roles:
    - role: k8s-cluster2-secondary-gateway

- hosts: cluster1WorkerNodes
  vars_files:
    - vars.yml
  roles:
    - role: k8s-cluster1-worker

- hosts: cluster2WorkerNode
  vars_files:
    - vars.yml
  roles:
    - role: k8s-cluster2-worker

- hosts: brokerNode
  vars_files:
    - vars.yml
  roles:
    - role: submariner-cluster1-broker

- hosts: cluster2PerfCollectorNode
  vars_files:
    - vars.yml
  roles:
    - role: submariner-cluster2

# Skip role if an external TSDB collector is defined in vars.yml
- hosts: cluster2WorkerNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-grafana
      when: external_grafana_collector | default('', true) | trim == ''

- hosts: cluster2WorkerNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-netserver

- hosts: brokerNode
  vars_files:
    - vars.yml
  roles:
    - role: deploy-netperf

