---
# tasks file for k8s-cluster1-worker

- name: Set the new hostname
  command: sudo hostnamectl set-hostname {{ hostname }}

- name: Pause for 10s to allow for the hostname change to stabalize
  pause:
    seconds: 10

- name: Display the k8s join token on the worker node
  debug:
    msg: "{{ hostvars[groups['brokerNode'][0]]['k8s_token'] }}"

- name: Display the k8s master IP address on the worker node used to join
  debug:
    msg: "{{ k8s_master }}"

- name: Install k3s on worker nodes
  vars:
    K8S_TOKEN: "{{ hostvars[groups['brokerNode'][0]]['k8s_token'] }}"
    K8S_MASTER: "{{ k8s_master }}"
  shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ K8S_MASTER }}:6443 K3S_TOKEN={{ K8S_TOKEN }} sh -
  ignore_errors: True
