---
# tasks file for submariner-cluster1-broker
- name: Register the private address of the EC2 host
  shell: hostname -I | awk "{print \$1}"
  register: node_ip

- name: Change the owner of the home dir
  shell: "sudo chown -hR {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/"

- name: Verify kubectl cmd
  command: kubectl get pods --all-namespaces --kubeconfig /home/{{ ansible_user }}/config

- name: Install Submariner
  shell: |
    curl -Ls https://get.submariner.io/ > /home/{{ ansible_user }}/install-sub
    chmod +x /home/{{ ansible_user }}/install-sub
    /home/{{ ansible_user }}/install-sub
    sudo cp /root/.local/bin/subctl /usr/local/bin/subctl

- name: Pause for 2s to allow for convergence
  pause:
    seconds: 2

- name: Label the node as a gateway
  command: kubectl label node {{ hostname }} submariner.io/gateway=true --overwrite --kubeconfig /home/{{ ansible_user }}/config

- name: Pause for 5s to allow for stabilization
  pause:
    seconds: 5

- name: Start the submariner broker
  shell: |
    subctl --kubeconfig /home/{{ ansible_user }}/config deploy-broker \
    --components service-discovery,connectivity

- name: Wait for submariner-operator to become ready
  command: kubectl wait --for=condition=ready pod -l name=submariner-operator --timeout=60s -n submariner-operator --kubeconfig /home/{{ ansible_user }}/config

- name: Pause for 20s to allow for stabilization
  pause:
    seconds: 20

- name: Change the owner of the home dir
  shell: "sudo chown -hR {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/"

- fetch:
    src: /home/{{ ansible_user }}/broker-info.subm
    dest: ./
    flat: true

- name: Pause for 2s to allow for stabilization
  pause:
    seconds: 2

# Uncomment for active/active HA experimental branch
- name: Join the submariner node to the broker
  shell: |
    subctl --kubeconfig /home/{{ ansible_user }}/config \
    join /home/{{ ansible_user }}/broker-info.subm \
    --clusterid {{ hostname }} \
    --clustercidr={{ submariner_cluster_cidr_cluster1 }}  \
    --cable-driver {{ submariner_cable_driver }} \
    --nattport 4500 \
    --natt=false \

- name: Pause for 60s to allow for stabilization
  pause:
    seconds: 60

- name: Ensure the submariner-gateway pod is in ready state
  shell: kubectl wait --for=condition=ready pod -l app=submariner-gateway --timeout=120s -n submariner-operator --kubeconfig /home/{{ ansible_user }}/config
